syntax enable
set encoding=utf-8

" {{{ Tab stop configurations
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab
set hidden
" }}}

" {{{ UI configurations
set cc=120
set number
set showcmd
set cursorline
set laststatus=2
set backspace=2
set t_Co=256

set guioptions-=r

set wildmenu
set lazyredraw
set showmatch
" }}}

" {{{ Searching configurations
set incsearch
set hlsearch
" }}}

" {{{ Folding configurations
set foldenable
set foldlevelstart=10
set foldmethod=marker
" }}}

" {{{ Shortcut mappings
noremap <C-j> <C-w><C-j>
noremap <C-k> <C-w><C-k>
noremap <C-l> <C-w><C-l>
noremap <C-h> <C-w><C-h>
noremap <C-t> :TagbarToggle<CR>
" }}}


set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'L9'
Plugin 'tpope/vim-fugitive'
Plugin 'chriskempson/base16-vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'jlanzarotta/bufexplorer'
Plugin 'Raimondi/delimitMate'
Plugin 'tmhedberg/matchit'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'klen/python-mode'
Plugin 'ervandew/supertab'
Plugin 'godlygeek/tabular'
Plugin 'majutsushi/tagbar'
Plugin 'tomtom/tlib_vim'
Plugin 'edkolev/tmuxline.vim'
Plugin 'mbbill/undotree'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'vim-ctrlspace/vim-ctrlspace'
Plugin 'easymotion/vim-easymotion'
Plugin 'airblade/vim-gitgutter'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'
Plugin 'tpope/vim-surround'
Plugin 'jmcantrell/vim-virtualenv'

call vundle#end()            " required
filetype plugin indent on    " required

" {{{ Python mode configurations
let g:pymode_rope=0

let g:pymode_doc=1
let g:pymode_doc_key='K'

let g:pymode_lin=0

let g:pymode_virtualenv=1

let g:pymode_breakpoint=1
let g:pymode_breakpoint_key='<leader>b'

let g:pymode_syntax=1
let g:pymode_syntax_all=1

let g:pymode_syntax_indent_errors=g:pymode_syntax_all
let g:pymode_syntax_space_errors=g:pymode_syntax_all

let g:pymode_folding=0

nmap <Leader>R :PymodeRun<cr>
" }}}

" {{{ Syntastic configurations
let g:syntastic_auto_loc_list=1
let g:syntastic_loc_list_height=5

let g:syntastic_python_checkers=['flake8']
let g:syntastic_python_flake8_args='--ignore=E501,E124'
" }}}

map / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)

map n <Plug>(easymotion-next)
map N <Plug>(easymotion-prev)

let g:EasyMotion_startofline=0

nnoremap <Leader>tt :UndotreeToggle<cr>

let airline_theme='base16'

source ~/.vimrc_background
