source $HOME/.config/antigen.zsh

antigen use oh-my-zsh

# Bundles from the default repo
antigen bundle git
antigen bundle git-extras
antigen bundle heroku
antigen bundle pip
antigen bundle command-not-found
antigen bundle vi-mode
antigen bundle tmux

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme ys

antigen apply

export TERM=xterm-256color

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
